In [3]:
import numpy as np
c=np.random.randn(2,3,4)
c

array([[[ 0.8366834 , -0.96683664, -0.78037487, -1.0221227 ],
        [ 0.31917005,  1.40829566, -0.77276369,  2.25720763],
        [ 1.06166655,  0.91126706,  0.86530742,  0.87679216]],

       [[-1.13373374,  0.03980745,  0.72335745, -0.311887  ],
        [-0.88158311, -0.73435371, -0.4356313 , -0.8102068 ],
        [-0.72584853, -0.34633288, -0.45435068,  1.02756625]]])

In [1]:
import numpy as np
def n(x):
    return np.dot(np.random.randn(2,3),np.dot(np.random.randn(3,3),x.T))
x=np.array([22,35,86])
y=n(x)
y

array([-98.58178276, 305.10994918])

In [12]:
import tensorflow as tf
print(tf.__version__)
a=tf.constant(1.0)
b=tf.constant(3.0)
c=a+b
print(c)
print(c.numpy())
quit()

2.3.1
tf.Tensor(4.0, shape=(), dtype=float32)
4.0


In [3]:
import tensorflow as tf
rank_0_tensor=tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
import tensorflow as tf
rank_2_tensor=tf.constant([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
print(rank_2_tensor)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]], shape=(4, 4), dtype=int32)


In [7]:
import tensorflow as tf
rank_3_tensor=tf.constant([
    [[1,2,3,4,1,1],
     [5,6,7,8,1,1],
     [9,10,11,12,1,1],
     [13,14,15,16,1,1],
     [1,1,1,1,1,1,]],
    [[1,2,3,4,1,1],
     [5,6,7,8,1,1],
     [9,10,11,12,1,1],
     [13,14,15,16,1,1],
     [1,1,1,1,1,1,]],
        [[1,2,3,4,1,1],
     [5,6,7,8,1,1],
     [9,10,11,12,1,1],
     [13,14,15,16,1,1],
     [1,1,1,1,1,1,]],
        [[1,2,3,4,1,1],
     [5,6,7,8,1,1],
     [9,10,11,12,1,1],
     [13,14,15,16,1,1],
     [1,1,1,1,1,1,]]
])
print(rank_3_tensor)

tf.Tensor(
[[[ 1  2  3  4  1  1]
  [ 5  6  7  8  1  1]
  [ 9 10 11 12  1  1]
  [13 14 15 16  1  1]
  [ 1  1  1  1  1  1]]

 [[ 1  2  3  4  1  1]
  [ 5  6  7  8  1  1]
  [ 9 10 11 12  1  1]
  [13 14 15 16  1  1]
  [ 1  1  1  1  1  1]]

 [[ 1  2  3  4  1  1]
  [ 5  6  7  8  1  1]
  [ 9 10 11 12  1  1]
  [13 14 15 16  1  1]
  [ 1  1  1  1  1  1]]

 [[ 1  2  3  4  1  1]
  [ 5  6  7  8  1  1]
  [ 9 10 11 12  1  1]
  [13 14 15 16  1  1]
  [ 1  1  1  1  1  1]]], shape=(4, 5, 6), dtype=int32)


In [10]:
import tensorflow as tf
a=tf.constant([[1,2],
              [3,4]])
print(tf.argmax(a,0))

tf.Tensor([1 1], shape=(2,), dtype=int64)


In [13]:
import tensorflow as tf
x=tf.constant(1.0)
with tf.GradientTape(persistent=True) as t:
    t.watch(x)
    y=tf.multiply(x,x)+tf.exp(x)
dy_dx=t.gradient(y,x)
del t
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=4.7182817>