In [1]:
import numpy as np
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
a=np.arange(0,9).reshape(3,3)
b=np.ones((3,3))
np.dot(a,b)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [7]:
a=np.random.random(12)
A=a.reshape(3,4)

In [9]:
def sigmoid(a):
    b=1/(1+np.exp(-a))
    return b
sigmoid(4)

0.9820137900379085

In [10]:
def tanh(a):
    b=(np.exp(a)-np.exp(-a))/(np.exp(a)+np.exp(-a))
    return b

In [21]:
def ReLU(X):
    return np.max(x,0)
x=[-1,1]
ReLU(x)

1

In [26]:
def ReLU(x,w=np.array([-0.21,0.3,0.7])):
        return np.max(w.dot(np.array(x)))
ReLU([1,0,1])


0.49

In [25]:
def logi(x,w=np.array([-0.21,0.3,0.7])):
    return sigmoid(w.dot(np.array(x)))
logi([1,0,1])

0.6201064323430902

In [35]:
def And (x1,x2):
    return np.int(np.round(sigmoid(np.array([x1,x2]).dot(np.array([20,20]))-30)))
And(0,1)

0

In [34]:
def Or (x1,x2):
    return np.int(np.round(sigmoid(np.array([x1,x2]).dot(np.array([20,20]))-10)))
Or(0,1)

1